##
## Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
## Licensed under the MIT License.
##

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: check-merge-conflict
-   repo: local
    hooks:
    -   id: lintrunner
        name: lintrunner
        entry: lintrunner
        language: python
        additional_dependencies:
          - lintrunner==0.12.7
          - lintrunner-adapters==0.12.4
          - clang-format==16.0.1
        types: [file]
        args: [--apply-patches]
        require_serial: true
