#!/usr/bin/env python3
"""
cmake/scan_scheme_deps.py — Parse Chez Scheme .sls files and generate
CMake custom commands for parallel compilation.

Usage:
  python3 scan_scheme_deps.py
    --scheme-dir <scheme-src>   # scheme/ source directory
    --rime-dir   <rime-src>     # rime source directory (external, not compiled)
    --obj-dir    <obj-dir>      # build-tree directory for .so files
    --scheme-bin <path/scheme>  # Chez Scheme binary (from ExternalProject)
    --libdirs    <dirs>         # --libdirs string passed to scheme
    --script     <path>         # path to compile_one_lib.ss
    --output     <file.cmake>   # output CMake include file
"""

import argparse
import os
import re
import sys
from pathlib import Path


# Libraries that live outside the crest scheme/ tree — never compiled by us.
EXTERNAL_PREFIXES = frozenset([
    "rnrs", "chezscheme", "rime", "r6rs", "scheme",
])


def is_external(lib_name_tuple):
    return lib_name_tuple[0] in EXTERNAL_PREFIXES


def parse_sls(path):
    """Return (library_name_tuple, [import_name_tuple, ...]) for a .sls file."""
    text = Path(path).read_text(encoding="utf-8")
    # Strip line comments
    text = re.sub(r";[^\n]*", "", text)
    # Strip block comments #| ... |#
    text = re.sub(r"#\|.*?\|#", "", text, flags=re.DOTALL)

    # Extract (library (name parts...)) — first occurrence
    lib_match = re.search(r"\(library\s+\(([^)]+)\)", text)
    if not lib_match:
        return None, []
    lib_name = tuple(lib_match.group(1).split())

    # Extract all (import ...) blocks; each sub-list is a library name
    imports = []
    for imp_match in re.finditer(r"\(import\b", text):
        start = imp_match.start()
        depth, i = 0, start
        while i < len(text):
            if text[i] == "(":
                depth += 1
            elif text[i] == ")":
                depth -= 1
                if depth == 0:
                    block = text[start : i + 1]
                    # Each top-level (...) inside the import block is a library name
                    inner = block[len("(import") :]
                    for m in re.finditer(r"\(([^()]+)\)", inner):
                        parts = tuple(m.group(1).split())
                        # Filter: must look like a library name (no keywords, no numbers)
                        if (len(parts) >= 1
                                and all(re.match(r"[\w/.-]+$", p) for p in parts)
                                and not parts[0].startswith(":")):
                            imports.append(parts)
                    break
            i += 1

    return lib_name, imports


def lib_name_to_rel_path(name_tuple):
    """(mlir core ir) → 'mlir/core/ir'  (no extension)."""
    return "/".join(name_tuple)


def find_sls_files(scheme_dir):
    """Walk scheme_dir and return all .sls files as relative paths."""
    result = []
    root = Path(scheme_dir)
    for p in sorted(root.rglob("*.sls")):
        result.append(str(p.relative_to(root)))
    return result


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scheme-dir", required=True)
    ap.add_argument("--rime-dir",   required=True)
    ap.add_argument("--obj-dir",    required=True)
    ap.add_argument("--scheme-bin", required=True)
    ap.add_argument("--script",     required=True)
    ap.add_argument("--output",     required=True)
    args = ap.parse_args()

    scheme_dir = args.scheme_dir
    obj_dir    = args.obj_dir
    scheme_bin = args.scheme_bin
    script     = args.script
    rime_dir   = args.rime_dir

    # ── Scan all .sls files ────────────────────────────────────────────────────
    sls_files = find_sls_files(scheme_dir)
    print(f"[scan_scheme_deps] Found {len(sls_files)} .sls files", file=sys.stderr)

    # Map: library_name_tuple → relative_path (without extension)
    lib_to_rel = {}   # (mlir core ir) → "mlir/core/ir"
    rel_to_lib = {}   # "mlir/core/ir.sls" → (mlir core ir)
    imports_of = {}   # "mlir/core/ir.sls" → [(mlir core logging), ...]

    for sls in sls_files:
        lib_name, imports = parse_sls(os.path.join(scheme_dir, sls))
        if lib_name is None:
            print(f"[scan_scheme_deps] WARNING: no library decl in {sls}", file=sys.stderr)
            continue
        rel = sls[:-4]  # strip .sls
        lib_to_rel[lib_name] = rel
        rel_to_lib[sls] = lib_name
        imports_of[sls] = imports

    # ── Generate CMake ─────────────────────────────────────────────────────────
    lines = [
        "# Auto-generated by cmake/scan_scheme_deps.py — do not edit.",
        "# Re-generated every cmake configure run.",
        "",
        f"set(CREST_ALL_SCHEME_SO_FILES)",
    ]

    all_so_vars = []

    for sls in sls_files:
        lib_name = rel_to_lib.get(sls)
        if lib_name is None:
            continue
        rel  = sls[:-4]       # e.g. "mlir/core/ir"
        so   = rel + ".so"    # e.g. "mlir/core/ir.so"

        so_abs  = f"{obj_dir}/{so}"
        src_abs = f"{scheme_dir}/{sls}"

        # Determine DEPENDS: the .so files this library's imports produce
        dep_so = []
        for imp in imports_of.get(sls, []):
            if is_external(imp):
                continue
            imp_rel = lib_to_rel.get(imp)
            if imp_rel:
                dep_so.append(f"{obj_dir}/{imp_rel}.so")
            # If not found, it might be in rime — ignore

        dep_str = "\n          ".join([src_abs] + dep_so)

        cmake_var = "CREST_SO_" + rel.replace("/", "_").replace("-", "_")
        all_so_vars.append(cmake_var)

        lines += [
            f"# {lib_name_to_rel_path(lib_name)}",
            f"set({cmake_var} {so_abs!r})",
            f"add_custom_command(",
            f"  OUTPUT  {so_abs!r}",
            f"  COMMAND {scheme_bin!r}",
            f"          --script {script!r}",
            f"          {rel + '.sls'!r}",   # src-file (relative)
            f"          {scheme_dir!r}",      # src-dir
            f"          {obj_dir!r}",         # obj-dir
            f"          {rime_dir!r}",        # rime-dir
            f"  WORKING_DIRECTORY {scheme_dir!r}",
            f"  DEPENDS {dep_str}",
            f"  COMMENT \"Compiling Scheme library ({' '.join(lib_name)})\"",
            f"  VERBATIM",
            f")",
            "",
        ]

    # List of all .so files for make-boot-file
    all_so_list = "\n  ".join(f"${{{v}}}" for v in all_so_vars)
    lines += [
        f"set(CREST_ALL_SCHEME_SO_FILES",
        f"  {all_so_list}",
        f")",
        "",
        "add_custom_target(CrestSchemeLibs DEPENDS ${CREST_ALL_SCHEME_SO_FILES})",
    ]

    Path(args.output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[scan_scheme_deps] Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
